### ISSUE TITLE
Connection to TLS socket on mail server fails when javax.net.ssl.trustStorePassword is not provided

### ISSUE THREAD

**Issue by pjverity** [docker-library/openjdk#163]
You'll have to forgive me if this is expected behaviour, but I'm new to Docker and my knowledge of Java's security is a little hazy to say the least, but I have hit on an issue with trying to connect to an external mail server. I have a Spring Boot app (2.0.0.M7) that uses Spring's Mail library. Running outside of a container works fine, but when running in a Docker container I get a large stack trace whenever the application attempts to send mail.

At the deepest part of the exception chain is this:

```
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200) ~[na:na]
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) ~[na:na]
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86) ~[na:na]
```

At the other end is this:

```
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty. Failed messages: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:446) ~[spring-context-support-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:359) ~[spring-context-support-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:354) ~[spring-context-support-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	...
```

I have found that the only way to resolve this is to pass `-Djavax.net.ssl.trustStorePassword=changeit` as a `CMD` argument in the Dockerfile.

I'm using `FROM openjdk:9.0.1-11-jre` if that's any help. Also tried the JDK image for kicks but that made no difference.

**Comment by code-chris** [comment]
This is a known bug #145. Try the slim-Image instead.

**Comment by yosifkit** [comment]
Closing as duplicate of #145.

**Comment by pjverity** [comment]
Thanks - the slim image did work as advised.
