### ISSUE TITLE
[openjdk:8-jre-alpine] TextFragment Exception

### ISSUE THREAD

**Issue by x-jokay** [docker-library/openjdk#256]
Hi

I got the following error when using `openjdk:8-jre-alpine`.

```sh
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (Alpine 8.181.13-r0)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

```sh
java.lang.NullPointerException
	at org.jfree.text.TextFragment.calculateDimensions(TextFragment.java:230)
	at org.jfree.text.TextLine.calculateDimensions(TextLine.java:194)
	at org.jfree.text.TextBlock.calculateDimensions(TextBlock.java:171)
	at org.jfree.chart.block.LabelBlock.arrange(LabelBlock.java:313)
	at org.jfree.chart.block.BorderArrangement.arrangeNN(BorderArrangement.java:215)
	at org.jfree.chart.block.BorderArrangement.arrange(BorderArrangement.java:141)
	at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
	at org.jfree.chart.block.CenterArrangement.arrangeNN(CenterArrangement.java:286)
	at org.jfree.chart.block.CenterArrangement.arrange(CenterArrangement.java:100)
	at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
	at org.jfree.chart.block.FlowArrangement.arrangeNN(FlowArrangement.java:367)
	at org.jfree.chart.block.FlowArrangement.arrangeRR(FlowArrangement.java:285)
	at org.jfree.chart.block.FlowArrangement.arrange(FlowArrangement.java:160)
	at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:178)
	at org.jfree.chart.title.LegendTitle.arrange(LegendTitle.java:540)
	at org.jfree.chart.JFreeChart.drawTitle(JFreeChart.java:1320)
	at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1214)
	at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1399)
	at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1379)
	at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1364)
	at trend$_run_closure1.doCall(trend.gy:294)
	at trend$_run_closure1.doCall(trend.gy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.WebUtilities.catchToLog(WebUtilities.groovy:145)
	at trend.run(trend.gy:277)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1351)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:186)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:158)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:516)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
```

Seems to work fine when using `openjdk:8-jre` but not with Alpine Linux.

**Comment by wglambert** [comment]
It would seem you've encountered a contraindication with using alpine

https://github.com/docker-library/docs/tree/master/openjdk#openjdkversion-alpine
>The main caveat to note is that it does use [musl libc](http://www.musl-libc.org) instead of [glibc and friends](http://www.etalabs.net/compare_libcs.html), so certain software might run into issues depending on the depth of their libc requirements.

Perhaps create a small reproducible of the error and file it to https://bugs.alpinelinux.org/projects/alpine/issues
