### ISSUE TITLE
openjdk:13 can't run app compile with java13 --enable-preview

### ISSUE THREAD

**Issue by mymbrooks** [docker-library/openjdk#362]
Dockerfile
`FROM openjdk:13
VOLUME /tmp
ADD QIJava-0.0.1-SNAPSHOT.jar qi.jar
RUN bash -c 'touch /qi.jar'
ENV JAVA_OPTS="--enable-preview"
EXPOSE 83
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:88","--enable-preview","-jar","/qi.jar"]`

It'a springboot app, in openjdk:12 works fine.When I upgrade to openjdk:13 the app can't run with this error:

docker logs java
Listening for transport dt_socket at address: 88
Exception in thread "main" java.lang.UnsupportedClassVersionError: qi/ruibu/Application (class file version 56.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 57.65535
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:515)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:423)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:417)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:416)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

I can print version info:
docker run --rm -it openjdk:13 java --enable-preview -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)

**Comment by wglambert** [comment]
>(class file version 56.65535) was compiled with preview features that are unsupported.
>This version of the Java Runtime only recognizes preview features for class file version 57.65535

Looks like it's not backwards compatible for preview features

**Comment by mymbrooks** [comment]
> > (class file version 56.65535) was compiled with preview features that are unsupported.
> > This version of the Java Runtime only recognizes preview features for class file version 57.65535
> 
> Looks like it's not backwards compatible for preview features

Yeah, in Java 12 it works fine with preview features. I have to use Java 13 with no preview features now.

**Comment by robilad** [comment]
Preview features are release-specific by design. 

Quoting from http://openjdk.java.net/jeps/12

" A JVM implementation for Java SE $N must not define a class file that depends on the preview VM features of a different Java SE release, even if the JVM implementation would otherwise understand the class file's version. Specifically, ClassLoader.defineClass must fail for the bytes of the class file. This prevents the class files from running years into the future, long after the preview language features that were enjoyed by the developer have been removed or finalized in a different form. In essence, Java SE $N+1 does not claim backwards compatibility with the preview features of Java SE $N."
