### ISSUE TITLE
java:8-jre-alpine com.sun.image.codec.jpeg.ImageFormatException

### ISSUE THREAD

**Issue by jasonmader** [docker-library/openjdk#79]
```
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 16 more
Exception in thread "liferay/document_library_image_processor-4" java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
	at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
	at com.sun.media.jai.codec.ImageDecoderImpl.decodeAsRenderedImage(ImageDecoderImpl.java:140)
	at com.liferay.portal.image.ImageToolImpl.read(ImageToolImpl.java:580)
	at com.liferay.portal.image.ImageToolImpl.read(ImageToolImpl.java:424)
	at com.liferay.portal.kernel.image.ImageToolUtil.read(ImageToolUtil.java:183)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorImpl._generateImages(ImageProcessorImpl.java:283)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorImpl.generateImages(ImageProcessorImpl.java:81)
	at com.liferay.portlet.documentlibrary.util.ImageProcessorUtil.generateImages(ImageProcessorUtil.java:53)
	at com.liferay.portlet.documentlibrary.messaging.ImageProcessorMessageListener.generate(ImageProcessorMessageListener.java:31)
	at com.liferay.portlet.documentlibrary.messaging.BaseProcessorMessageListener.doReceive(BaseProcessorMessageListener.java:36)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:72)
	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:67)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jasonmader** [comment]
also a problem using java:7-jre-alpine

**Comment by yosifkit** [comment]
I am not sure what is being run to cause the problem.  Is there a system library missing or is this an issue of it being openjdk and not oracle?

**Comment by jasonmader** [comment]
It turns out to just being openjdk and not oracle.

**Comment by md5** [comment]
@jasonmader It looks like JAI doesn't have compatible licensing to allow it to be distributed with OpenJDK. You may be able to install it yourself though: http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-java-client-419417.html#jai-1_1_2_01-oth-JPR
